### PR TITLE
Support Re-select images from library

### PR DESCRIPTION
**Pull request by yrhorita**
Hi there,

I just added new feature supporting re-select images from library.
Not sure for every options(crop saving, filter, etc), but sample VC and my project works fine with it.

Any feedbacks are welcome. Thank you.

### CODE REVIEW

**Comment by s4cha** [comment]
Hi @yrhorita,

First of all thank you so much for starting out this improvement. Here is some feedback below.

1 - Could you explain the use case behind this feature, so that I get a real world example.
2 - I'd suggest setting the preselected items via a property and not the constructor. `public init(selected: [YPMediaItem], configuration: YPImagePickerConfiguration)` Indeed we want to keep the api as simple as possible for the classic use cases :)

PS: Excuse the late reply, we are victims of our success 😃

**Comment by NikKovIos** [comment]
@yrhorita 
Does this MR do the same? https://github.com/Yummypets/YPImagePicker/pull/370

**Comment by buptjz** [comment]
I think this feature is very useful. Image when the users select some pics, and then they want add some more, this time we should give the hints what they've already selected and avoid repeated selections.

**Comment by NikKovIos** [comment]
Closed because outdated and author leaved a conversation.

**Pull request closed without merging**
