### PR TITLE
Fixes SPM integration

### PR DESCRIPTION
**Pull request by s4cha**
- Reorganizes folder structure to comply with SPM guidelines
- Fixes resources module linking in xibs
- Adapts Podspec to new folder structure
- Makes Example project use SPM

A big plus is that the example project is now available to people that are not using Cocoapods.

### CODE REVIEW

**Comment by NikKovIos** [comment]
In this branch the cocoapods is broken, so I gonna close this PR, because for now it's easier to test with cocoapods and spm together. Also I did changed the xib UI to code implementation, so this changes for now not critical.

**Comment by tsahi-deri** [comment]
Hey @NikKovIos 
Does this fix included in you latest release 5.2.1 ?

**Comment by NikKovIos** [comment]
@tsahi-deri yes, should be. tell me if not working.

**Comment by rehannali** [comment]
Hi, Camera crash fix is not available in the latest changes. It is still broken and #713 is not merged in latest update and app is crashing if you don't give photos permission.

**Pull request closed without merging**
