### PR TITLE
Fix Issue #546 regression on preSelectItemOnMultipleSelection

### PR DESCRIPTION
**Pull request by peymankh4**
Issue #546 

The implementation of the fix is not as clean as I like it to be, maybe @s4cha can have a look as well and have better insights on if this is the right way of doing it.

### CODE REVIEW

**Comment by victormihaita** [comment]
Can this be merged?

**Comment by peymankh4** [comment]
It'd be great if we could. Been sitting on this for quite some time.

**Comment by victormihaita** [comment]
Could you fix conflicts just to have it ready? :)

**Comment by peymankh4** [comment]
@victormihaita Actually seems the issue has been fixed on master. Can you confirm as well and if that's the case we can close this PR. Updated the branch anyway.

**Comment by peymankh4** [comment]
Closing this as it's already fixed on master.

**Comment by said13** [comment]
Why after pod install / pod update I still have old code? 
Pod updated to 4.4.0 bug code is old

**Pull request closed without merging**
