### PR TITLE
Add auto trim for videos from device library using trimmerMaxDuration

### PR DESCRIPTION
**Pull request by mendesbarreto**
This commits adds the request from issue #341. 

This case occurs when the user already has a video selected and enables a multiselection to pick more than one type of media (video or image), so, the trimmer step becomes optional.

### CODE REVIEW

**Comment by Ludotrico** [comment]
Has this feature been implemented? It is crucial functionality. @mendesbarreto @heitara

**Review by heitara — APPROVED** [review]
It would be best if all the white-spaces are not changed, because this will reduce the diff file massively.

**Comment by mendesbarreto** [comment]
> It would be best if all the white-spaces are not changed because this will reduce the diff file massively.

About that, When I push some commit to GitHub I have a script which runs automatically some swiftlint rules like white spaces. I will try to remove what it has done.

**Comment by mendesbarreto** [comment]
> It would be best if all the white-spaces are not changed because this will reduce the diff file massively.

@heitara I tried to remove all the changes Swiftlint did on the code, I tried my best but how the project does not have any spacing pattern, some times the lines have space other not, it makes hard to guess, after my last commit.

But It's done =) . If you want the next pull request we can put Swiftlint and you can define what kind of rules you like or not on the project, it will simply the contribution workflow and avoid this kind of problem and of course, this will increase the cohesion of your codebase.

Thx

**Comment by heitara** [comment]
Completely agree. Code style refactoring should be done in separate commit without any functionality change.

**Comment by Ludotrico** [comment]
I am new to the concept of pull requests. Will there be some sort of notification when this branch is merged into the master? Will cocoa pods automatically add the new code to an existing Xcode project?
@heitara @mendesbarreto

**Comment by mendesbarreto** [comment]
> I am new to the concept of pull requests. Will there be some sort of notification when this branch is merged into the master? Will cocoa pods automatically add the new code to an existing Xcode project?
> @heitara @mendesbarreto

Hello @Ludotrico, To receive a notification when a new version is available you can go to "Watch" option at the header of the site and choose the option "release only" or to receive all notification you can choose the option "Watching"

Screen Shot 2020-07-27 at 5 51 38 PM

**Comment by Ludotrico** [comment]
Thanks, just did that.
Will cocoa pods automatically add the newly merged code to an existing Xcode project? 
@mendesbarreto

**Comment by mendesbarreto** [comment]
> Thanks, just did that.
> Will cocoa pods automatically add the newly merged code to an existing Xcode project?
> @mendesbarreto

@Ludotrico it will depend on how you wrote this dependency in your file, I believe the next pod version will be v4.3.0, so, if you wrote like this:

```
pod 'YPImagePicker' 
#OR
pod 'YPImagePicker' ~> 4.2
```

The next time you run ```pod update``` the lib will be updated

**Comment by Ludotrico** [comment]
Sounds good, thank you for the clarification. Any reason why this branch is being delayed?
@mendesbarreto

**Review by NikKovIos — APPROVED** [review]

**Comment by Ludotrico** [comment]
Thank you for the clarification, now what is the procedure to get it merged? I see that NikKovlos has approved it, how many more approvals does it require? Who can approve it?
@mendesbarreto

**Comment by mendesbarreto** [comment]
Hello Guys, 

I can't merge because I don't have any write access to the repo:

Screen Shot 2020-08-03 at 10 03 41 AM

Thx you all.

**Comment by NikKovIos** [comment]
@s4cha must approve it too

**Comment by s4cha** [comment]
Great work 🤩

**Comment by Ludotrico** [comment]
atta boy @mendesbarreto

**Pull request merged**
