### PR TITLE
Provides an api endpoint to customize wordings

### PR DESCRIPTION
**Pull request by s4cha**
The wordings can be customized like so: 
```swift
config.wordings.libraryTitle = "Gallery"
```

### CODE REVIEW

**Review by NikKovIos — COMMENTED** [review]
Great and fast! Some points, that makes me doubt:
Maybe it's better to make YPWordings a class. Correct me if the structure is reallocating every time its property is changed?
Is it necessary to make a YPPermissionDeniedPopup a singletone? With SOLID it's better to use as less singletones as possible.

**Comment by s4cha** [comment]
@NikKovIos Concerning `YPWordings`, 
The structs should only be copied when passed around, from what I unserdstand. So modifying one property doesn't reallocate the whole thing :)
Additionally, `YPImagePickerConfiguration` being a `struct` itself it would make little sense embedding a reference type into a value type.
 As a general rule, I quite like the idea of using struct by default, and only using `class` when we explicitly need reference semantics, or inheritance.

I definitely agree with you on the singleton codesmell, I'm going to refactor it to remove it :)

Cheers,

**Comment by s4cha** [comment]
@NikKovIos The main issue was accessing the config from the `PermissionCheckable` extension, but once again protocols to the rescue :
`extension PermissionCheckable where Self: UIViewController, Self: HasConfiguration`
Bye bye singleton !

**Comment by s4cha** [comment]
@NikKovIos good for you?

**Review by NikKovIos — APPROVED** [review]

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/issues/48

**Pull request merged**
