### PR TITLE
Added fetchOptions as param

### PR DESCRIPTION
**Pull request by mdb1**
With this code, developers can init the library with a PHFetchOptions configuration.
By doing that they will have the power to restrict the images shown by date for example.

```
let fromDate = Calendar.current.date(byAdding: dateComponent, to: Date())!
let toDate = Calendar.current.date(byAdding: dateComponent, to: Date().addingTimeInterval(5.0 * 60.0))!
let options = PHFetchOptions()
options.predicate = NSPredicate(format: "creationDate > %@ && creationDate < %@", fromDate as CVarArg, toDate as CVarArg)
        
 //Just a way to set order
let sortDescriptor = NSSortDescriptor(key: "creationDate", ascending: true)
options.sortDescriptors = [sortDescriptor]
        
var config = YPImagePickerConfiguration()
config.screens = [.library]
config.library.mediaType = .photo
config.library.onlySquare  = false
config.library.minNumberOfItems = 1
config.library.maxNumberOfItems = 10
config.albumName = "Nightlog"
        
let picker = YPImagePicker(configuration: config, options: options)
picker.imagePickerDelegate = self
```

### CODE REVIEW

**Comment by s4cha** [comment]
Hi @mdb1,

First of all, thanks a ton for taking the time to contribute, this is really appreciated 👏 
Secondly, I really like the idea of having custom predicates to fine tune even further what the library displays, very powerful!

I have just one point to discuss.

Is there a specific reason for using a separate "options" param?

I'd suggest we put that in the `library` section of the `YPImagePickerConfiguration` struct.

The usage would be the following:

```swift
// Only show library pictures from the last 3 days
let threDaysTimeInterval: TimeInterval = 3 * 60 * 60 * 24
let fromDate = Date().addingTimeInterval(-threDaysTimeInterval)
let toDate = Date()
let options = PHFetchOptions()
options.predicate = NSPredicate(format: "creationDate > %@ && creationDate < %@", fromDate as CVarArg, toDate as CVarArg)

//Just a way to set order
let sortDescriptor = NSSortDescriptor(key: "creationDate", ascending: true)
options.sortDescriptors = [sortDescriptor]

var config = YPImagePickerConfiguration()
// ...
config.library.options = options

let picker = YPImagePicker(configuration: config)
```

Indeed we ideally want to keep every customisation point via the configuration struct.

Hope this makes sense :)

PS: Here is the diff attached if you want to apply this modification:

[diff.txt](https://github.com/Yummypets/YPImagePicker/files/2248886/diff.txt)

Cheers,

**Comment by mdb1** [comment]
@s4cha Thanks for the feedback and the time to review the PR. I have applied the diff and I think that now the code is more simple.

**Comment by s4cha** [comment]
Awesome! 🚀

**Comment by Drakot** [comment]
Where is the documentation on this? I need to sort by modification date

**Pull request merged**
