### PR TITLE
Preserve selection when changing collections

### LINKED ISSUE #193: Multiple selections are cleared when albums changed.
**Describe the bug**

- Multiple selections are cleared when asset collections switched.

**To Reproduce**
1. Go to Gallery（Library）
2. Click on multiple selections button
3. Click on the title view ( `Gallery` )
4. Click any cells (e.g. `Camera Roll`) and switch albums.
5. Multiple selections are cleared.

**Expected behavior**
Selections should remain unchanged.

**Environment (please complete the following information):**
 - Xcode Version 9.3.1
 - Swift Version 4.1

**Installation Type**
 - Manual

**Additional context**

### PR DESCRIPTION
**Pull request by mpiechocki**
Attempt to resolve #193 

There will be a little refactor needed if #249 is merged first.
I'm not sure about one or two lines (you'll notice which ones, I guess ;p) but I couldn't find any bugs while testing it on a small example app.
This PR introduces a little change to the way selections are handled, so feel free to point out anything you think is not clear!

### CODE REVIEW

**Comment by s4cha** [comment]
@mpiechocki indeed I merged #249 first, I hadn't seen this one, my bad :) Could you check to fix the remaining conflict? You'll probably be faster than me.
Cheers !

**Comment by mpiechocki** [comment]
After a quick check, this should do the work, but please click through it before merging - It's been almost 3 months and I'm not 100% sure why this confilt happened :/

**Comment by s4cha** [comment]
@mpiechocki thank you so much! Taking a look now :)

**Comment by s4cha** [comment]
Ok the single image selection was broken but it's an easy fix :) The selection preservation across folders is one of the big awaited features so thank you so much for tackling this 🍾 !!!!

**Comment by mpiechocki** [comment]
I'm glad I could help ;) happy new year! :)

**Pull request merged**
