### PR TITLE
Configuration option to disable photos within the library 

### PR DESCRIPTION
**Pull request by portellaa**
Hello 👋 

First of all, nice lib, one of the best pickers i have tried and the one i choose for my current project.

So i have a requirement in my project, which is only support videos in the library viewer and so i decided to do the changes and submit a pull request 😅 (and 🙏)

So what did i change: 👇 

👉  Added new parameter in the configuration to support disable photos in
library
👉  Updated refreshMediaRequest to apply new filter

And it's basically that.

I left a comment and i would like to hear your thoughts around that, when the user doesn't selects photos neither videos, what should the library show.

Thanks 🍻 🙏

### CODE REVIEW

**Comment by s4cha** [comment]
@portellaa Thank you for the kind words 😃 🍾  ! 
This looks like a very nice addition and clean implementation to me 👌 !
I will have time to review and test this tomorrow, stay tuned :)
@NikKovIos Any thoughts ?

Have a good day sir!

**Comment by portellaa** [comment]
Hi guys 👋 

Do you have updates on this PR?

Cheers

**Comment by s4cha** [comment]
@portellaa Telepathy, I was about to write you
Sorry we took quite a long time polishing the multiple selection PR that just got merged.
I can finally take a look :)

**Comment by portellaa** [comment]
Niiice 😀

I will fix rebase the PR now, it seems that there is some conflicts.
We have released our App today in the AppStore, with this library. 
You have one more App using your library 🎉 😄

**Comment by s4cha** [comment]
Hey @portellaa don't bother I'm merging locally at the moment :)
That's really awesome to know! I think we gonna have a section in the readme to showcase the apps using it 👍

**Comment by s4cha** [comment]
Just merged but I think we still have a little issue, when changing albums, we need to hid albums that contain no photos I guess. I had a crash :) Have to go right now but I'll have time tomorrow to look at it.
Thank you SO much man!!!

**Comment by portellaa** [comment]
@s4cha i will look into it also. thanks and sorry for introduce the bug.

**Comment by s4cha** [comment]
@portellaa No problem, this happens :) I'm taking a look at the moment.

**Comment by s4cha** [comment]
@portellaa Ok I've got the fix :) Will push soon !!!

**Comment by s4cha** [comment]
https://github.com/Yummypets/YPImagePicker/commit/1cf71c1b8338f0be3e5c0392cedd3e9e19f4eca1 👍  That was easier than I thought :)

**Comment by portellaa** [comment]
awesome sir 🙇 nicely done 🎉

**Pull request merged**
