### PR TITLE
Add configuration of default multiple selection.

### LINKED ISSUE #310: Default multiple selection
**Is your feature request related to a problem? Please describe.**
Now, if we want to default multiple selection, we are needed to make minimum multiple section count `2`.

**Describe the solution you'd like**
Add default multiple section with bool in Configuration.

**Describe alternatives you've considered**
none.

**Additional context**
none.

### PR DESCRIPTION
**Pull request by s2mr**
This PR enables set default multiple image selction.

close #310

### CODE REVIEW

**Comment by iTofu** [comment]
👍

**Comment by rafalwojcik** [comment]
Can we make this merged to repo? I need this feature.

**Comment by s4cha** [comment]
@kzumu Thanks so much for taking the time to improve the picker ! 🏅 
PS: Please excuse the fact it took so long to review 🙏

**Comment by s4cha** [comment]
This is now up in https://github.com/Yummypets/YPImagePicker/releases/tag/4.0.0 🚀

**Pull request merged**
