### PR TITLE
Image with EXIF meta

### PR DESCRIPTION
**Pull request by Romixery**
In `didFinishPicking` function, we lose access of assets meta data(EXIF). Information like GPS, and capture device can not access from this point.
I wrote small patch that add `exifMeta` property to `YPMediaPhoto` class.

### CODE REVIEW

**Comment by s4cha** [comment]
@Romixery I'll have time tomorrow to look at it more carefully with more brain power but this looks like a great addition to me :)
@NikKovIos would love your input as well 👓 

Cheers,

**Comment by s4cha** [comment]
Just tried it and successfully getting the EXIF !
The amount of data attached to a picture is insane, quite scary actually 🙃 

It works as expected so it's a YES for me :)
I do suggest the following patch though
[changes.txt](https://github.com/Yummypets/YPImagePicker/files/2039651/changes.txt)
In the current implementation `requestImageData` is called twice, I think it would be better to integrate EXIF fetching along the existing `requestImageData` as done in the patch above :)


```
Optional(["PixelHeight": 3024, "DPIHeight": 72, "{Exif}": {
    ApertureValue = "1.695993715632365";
    BrightnessValue = "-1.957493018926466";
    ColorSpace = 65535;
    ComponentsConfiguration =     (
        1,
        2,
        3,
        0
    );
    DateTimeDigitized = "2018:05:24 22:15:59";
    DateTimeOriginal = "2018:05:24 22:15:59";
    ExifVersion =     (
        2,
        2,
        1
    );
    ExposureBiasValue = 0;
    ExposureMode = 0;
    ExposureProgram = 2;
    ExposureTime = "0.25";
    FNumber = "1.8";
    Flash = 16;
    FlashPixVersion =     (
        1,
        0
    );
    FocalLenIn35mmFilm = 28;
    FocalLength = 4;
    ISOSpeedRatings =     (
        160
    );
    LensMake = Apple;
    LensModel = "iPhone X back dual camera 4mm f/1.8";
    LensSpecification =     (
        4,
        6,
        "1.8",
        "2.4"
    );
    MeteringMode = 5;
    PixelXDimension = 4032;
    PixelYDimension = 3024;
    SceneCaptureType = 0;
    SceneType = 1;
    SensingMethod = 2;
    ShutterSpeedValue = "2.00051948051948";
    SubjectArea =     (
        2015,
        1511,
        2217,
        1330
    );
    SubsecTimeDigitized = 375;
    SubsecTimeOriginal = 375;
    WhiteBalance = 0;
}, "DPIWidth": 72, "Depth": 8, "Orientation": 6, "ProfileName": Display P3, "{MakerApple}": {
    1 = 9;
    12 =     (
        "28.25391",
        "99.6875"
    );
    13 = 33;
    14 = 4;
    15 = 2;
    16 = 7;
    2 = <35004b00 2e003b00 61005100 4e005300 55007100 49003300 41001800 1d003b00 4200d100 39003f00 63006500 6c006200 56004400 3f003500 40003400 3f003f00 38002001 1c014100 56007300 6c006500 58004500 36002c00 1a003500 33002c00 2d007e00 92015201 a4007100 51004f00 41002d00 1a001600 11001400 1f001600 2a003900 9000b701 0c02d100 9c008400 30001800 10000d00 10001700 0e001500 2b002900 39007b00 8701ef01 78004500 30002100 18001800 19001500 0c000a00 2c002b00 28003900 a500ff00 a9005100 34002900 29002f00 1e000d00 0c000c00 2b002c00 2a002a00 6e008100 76005e00 64007d00 2b002b00 13000e00 0d000b00 2b002b00 2c002a00 2d006400 6500a000 7c017000 23001d00 11000f00 0d000b00 2a002b00 2c002c00 29003300 63005b00 38009a00 9f003d00 14001000 0e000c00 2a002b00 2d002d00 2a002800 27002c00 30002e00 68003200 19001200 0f000d00 29002a00 2c002d00 2b002800 26002500 22002200 34002200 17001200 10000e00 29002a00 2c002e00 2c002900 27002600 23002100 30002000 24001500 10000f00 29002b00 2c002f00 2d002a00 27002700 33003200 24001c00 2f001600 13000f00 2a002c00 2d002f00 2e002b00 28002a00 49015100 5d004600 39001e00 0f000f00 2b002e00 2e002f00 2e002c00 28002700 30004b00 7c002700 15001400 0c002300>;
    20 = 5;
    23 = 8192;
    25 = 0;
    26 = q825s;
    3 =     {
        epoch = 0;
        flags = 1;
        timescale = 1000000000;
        value = 828437237734833;
    };
    31 = 0;
    4 = 1;
    5 = 93;
    6 = 138;
    7 = 1;
    8 =     (
        "-0.05881023",
        "-0.941556",
        "0.1822958"
    );
}, "{TIFF}": {
    DateTime = "2018:05:24 22:15:59";
    Make = Apple;
    Model = "iPhone X";
    Orientation = 6;
    ResolutionUnit = 2;
    Software = "11.3";
    TileLength = 512;
    TileWidth = 512;
    XResolution = 72;
    YResolution = 72;
}, "ColorModel": RGB, "{GPS}": {
    Altitude = "1.424629535002555";
    AltitudeRef = 0;
    DateStamp = "2018:05:24";
    DestBearing = "51.75839653304442";
    DestBearingRef = T;
    HPositioningError = 12;
    ImgDirection = "51.75839653304442";
    ImgDirectionRef = T;
    Latitude = "44.86621166666666";
    LatitudeRef = N;
    Longitude = "0.559505";
    LongitudeRef = W;
    Speed = "0.8373284840469499";
    SpeedRef = K;
    TimeStamp = "20:15:58";
}, "PixelWidth": 4032])
```

**Comment by Romixery** [comment]
Thank you for your suggestion. Yes, your code is more optimized.

**Comment by s4cha** [comment]
@Romixery Ok then we can merge as is and I'll apply the patch afterwards. Thank you so much for taking the time to enable this cool feature, this is truly appreciated 🙏

**Pull request merged**
