### PR TITLE
logo design contribution

### PR DESCRIPTION
**Pull request by ihtiht**

### CODE REVIEW

**Comment by NikKovIos** [comment]
Nice 😊

**Comment by s4cha** [comment]
That is superb ! 😍 
Thank you so much @ihtiht !!!

**Comment by s4cha** [comment]
I added you in the Contributors section of the Readme 👍

**Comment by ihtiht** [comment]
I am happy to do this. We've done a good job with your ideas. Take care of yourself boys.. 👍

**Pull request merged**
