### PR TITLE
[WIP] - Starts implementing multiple selection

### PR DESCRIPTION
**Pull request by s4cha**
@NikKovIos  Not ready for merge yet.

Here we can discuss and refine the api.

At the moment I was thinking something like (name not definitive)
```swift
config.maxNumberOfPhotos = 12
```
Any value over one would enable the multiple selection, default value being 1.

### CODE REVIEW

**Comment by NikKovIos** [comment]
I have some questions:
Is this would be a one delegate/callback with array or two like in [Fusuma](https://github.com/ytakzk/Fusuma):
```swift
func fusumaImageSelected(image: UIImage, source: FusumaMode) {}
func fusumaMultipleImageSelected(images: [UIImage], source: FusumaMode) {}
```
We should implement the functional to select multiple images and videos. For example two images and two videos at once. So it should be a way to give them to user in callback. What do you think about it?

Also the var should be called `maxNumberOfItems` or something like.

**Comment by s4cha** [comment]
@NikKovIos Good catch!

I'm all for selecting photos and videos at the same time.
Maybe we'll have to introduce a `MediaItem` Model wrapping both photos and videos so that we can return a strongly typed`[MediaItem]`.
This `MediaItem` abstraction could be a good place to encapsulate things like thumbnails, original/cropped/filtered photo for example.

Concerning the callbacks, having one sounds simpler on paper but it complexifies the usage for the vast majority using simple photo/video, because they would now need to access the media through `items.first` for instance. Having two would also have the cool benefit of leaving the api unchanged for people upgrading the tool. So I'd lean on the `two` callbacks side :)

`maxNumberOfItems` sound more appropriate indeed, I'd missed the fact that videos can be selected as well :)

Another tricky topic is about cropping and filtering,

1 - They disabled entirely in multiple selection.
2 - We push the crop/ filter screens once per item selected
3 - We have a new screen with a scroll, ala instagram, to filter out images one by one afterwards.

Instinctively I'd say number 1 or 2, number 3 adding quite a lot of work if we want to have this feature out in a reasonable timeframe.

**Comment by NikKovIos** [comment]
Exactly what i thought (about 'MediaItem')! 

About crop and filter - i think we should make it like in Instagram now. The reason: library used by a developers. Lot of customers look at the Instagram and say "wow, i need the same".
Otherwise i didn't look at the architecture and code very deep, so can't say how much time it could take. 1 way looks good, but i prefer the insta'like solution. 

About callbacks:
What do you think about make one delegate with one func - array of MediaItem. And later deprecate a callback?

If you need an emergence connect - you can write me in what'sapp 89996360337

**Comment by NikKovIos** [comment]
Connect me please via Whats'app (89996360337), Skype (a_yoguk) or other messenger. In order to sinchronize and not to do the same job.

**Comment by s4cha** [comment]
@NikKovIos Thinking about it I'd say 1, and we'll add filtering/cropping ala instagram afterwards.
I think whatever we can split to have atomic features as possible is good as it maintains momentum.

About callbacks, I agree with one, because it's simpler api-wise. The single one can be deprecated after so that old users don't have to change their implementation.

**Comment by NikKovIos** [comment]
Ok, so resume:
1) If user select multiple items and click next, than the delegate method would fire with 2 or more MediaItems. 
2) Selection for single item stays unchanged. 
3) Selection for single item also fires a delegate method. 
Right?

**Comment by s4cha** [comment]
@NikKovlos Yes :)

**Comment by cwestMobile** [comment]
Hows this goin?

**Comment by NikKovIos** [comment]
I've implemented a raw version. There is bug when selection multiple images and videos. It's when selecting images and then videos. I think this is with crop. You should check and maybe implement a crop service.

    [Unknown process name] CGImageCreateWithImageProvider: invalid image size: 0 x 0.

I did'n figure out what is it for now.

The next step is to integrate video cropping. The flow would looks like:  
1) Select multiple items
2) Go to `SelectionGalleryVC` _(can add filters there like in instagramm)_  
3) Tap on one of image, there would present filterVC for photo and video. For video it would be additional (except filters) functional to crop the video.
4) Edit and go back to `SelectionGalleryVC` 
5) Press next. Finish.

Also there are new and change Localization keys to translate.

**Review by NikKovIos — CHANGES_REQUESTED** [review]
Not finished yet

**Comment by s4cha** [comment]
@NikKovIos the work you're doing is nothing short of amazing  💪!  Can't wait for the new version to be out :)

**Comment by goribchat** [comment]
After using this line config.maxNumberOfPhotos = 12.it is showing ->

Value of type 'YPImagePickerConfiguration' has no member 'maxNumberOfPhotos'
How to resolve this?

**Comment by NikKovIos** [comment]
@goribchat it's renamed to `maxNumberOfItems`. Check the configuration API before asking please. Respect our time, man)

**Review by NikKovIos — COMMENTED** [review]
Is it ok to have this title (trim) and choose the cover? I mean if we trimming only it's ok, but you can choose a cover on that screen too, so the filter title fit's better here, imho)

**Comment by s4cha** [comment]
@NikKovIos I do agree, Actually instagram has no title on those screens. In our case "filter" is not really adapted for videos since we do not support filters yet. Should we choose something like "edit" ?

**Comment by NikKovIos** [comment]
Wof, such a big merge! 😀

**Pull request merged**
