### PR TITLE
Allow no selection when multi-selecting

### LINKED ISSUE #247: can`t deselect 1 image if the max allowed image is more than 1
after i select several images and then I want to deselect them, i can`t deselect 1 image if the max allowed image is more than 1, 
if i want to deselect the 1 image I need to select another image and deselect the first

### PR DESCRIPTION
**Pull request by mpiechocki**
Attempt to fix #247, as I can't see the point of not allowing this.

I also tried to maintain `selection` variable so it always contains what is actually selected (as I think this is more readable and understandable and reliable). Hopefully I didn't break anything else! ;)

### CODE REVIEW

**Comment by mpiechocki** [comment]
And also, I have no idea how to make codebeat check pass :D

**Comment by NikKovIos** [comment]
Hi @mpiechocki! Thank you for your PR. I checked the code briefly and want to ask you to test the app more carefully. Because you can fix one feature, but produce bugs.
Please test when in the library would be big photos, videos. Test with multiple selection staring from different items (not only first or only photos).

Waiting for your answer :)

**Comment by mpiechocki** [comment]
Hey, @NikKovIos! After playing around with a simple app (videos, images and all the edge cases I could come up with) I couldn't break it, so I assume it's working pretty well ;) Of course, further tests (and any automated tests :p) would be appreciated, but for now, I don't know if I can provide any more evidence :p

**Comment by mpiechocki** [comment]
And I think now we can get rid of a lot of code from
```
public func selectedMedia(photoCallback: @escaping (_ photo: YPMediaPhoto) -> Void,
                              videoCallback: @escaping (_ videoURL: YPMediaVideo) -> Void,
                              multipleItemsCallback: @escaping (_ items: [YPMediaItem]) -> Void)
```

So that whole `YPLibraryVC` now works on the `selection` property only.
I think it's much clearer now to understand and to work on further.
Again, I myself couldn't find any bugs after those changes, be it on simulator or actual device. But without automated tests I really cannot be sure ;)

**Comment by s4cha** [comment]
I don't remember why I did that at the time, our guidelines were always to stick with what instagram does and they allow empty selection so it's a win :) Thanks @mpiechocki for this !! 🚀

**Pull request merged**
